name: node20
on:
  push:
    branches: [ 'dev' ]
env:
  NAMESPACE: odiliamad
  REPOSITORY: codebstach
  TAG: latest
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
  
permissions:
  contents: read
  issues: write  
  
jobs:
  buil_push:
    runs-on: ubuntu-latest
    env: ${{ github.head_ref || github.ref_name }} 
    
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v4 
        
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
  
